"""crear tablas iniciales ms1

Revision ID: 6ca35b598ec2
Revises: 
Create Date: 2026-09-08 13:05:10.795095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ca35b598ec2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_migratoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Enum('Nacional', 'Internacional', 'Transito', name='nombre_categoria_migratoria'), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('tarifa >= 0', name='chk_categoria_tarifa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id_persona', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('equipaje',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_vuelo', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('peso > 0', name='chk_equipaje_peso'),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasajero',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('DNI', 'Pasaporte', 'Carnet de Extranjeria', name='tipo_documento'), nullable=False),
    sa.Column('numero_documento', sa.String(length=15), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_migratoria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('tipo_documento', 'numero_documento', name='uq_pasajero_documento')
    )
    op.create_table('ticket',
    sa.Column('id_ticket', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('estado_boarding', sa.Enum('Emitido', 'Check-in', 'Embarcado', 'No-show', 'Cancelado', name='estado_boarding'), server_default='Emitido', nullable=False),
    sa.Column('id_vuelo', sa.BigInteger(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.CheckConstraint("estado_boarding <> ''", name='chk_ticket_estado'),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_table('checkin',
    sa.Column('id_ticket', sa.BigInteger(), nullable=False),
    sa.Column('fecha_hora', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('counter', sa.String(length=10), nullable=True),
    sa.Column('con_equipaje', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id_ticket'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    op.drop_table('ticket')
    op.drop_table('pasajero')
    op.drop_table('equipaje')
    op.drop_table('persona')
    op.drop_table('categoria_migratoria')
    # ### end Alembic commands ###
